# Generated by Django 5.1.7 on 2025-03-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='category',
            field=models.CharField(choices=[('arrays', 'Arrays'), ('strings', 'Strings'), ('linked_list', 'Linked List'), ('stacks', 'Stacks'), ('queues', 'Queues'), ('recursion', 'Recursion'), ('dynamic_programming', 'Dynamic Programming'), ('graph', 'Graph'), ('tree', 'Tree'), ('greedy', 'Greedy'), ('bit_manipulation', 'Bit Manipulation'), ('math', 'Math'), ('miscellaneous', 'Miscellaneous')], max_length=30),
        ),
    ]
